### ISSUE TITLE
[FEATURE REQUEST]: Adding `UnhollowerBaseLib` as deprecated for games that no longer use it

### ISSUE THREAD

**Issue by Arkhorse** [Slaynash/Lumbot#12]
### Is your feature request related to a problem? Please describe.

Currently LUM sees `UnhollowerBaseLib` being missing as simply a missing dependency. For games that used to use it, but no longer use it, this assumption is misleading

### Describe the solution you'd like

For games that dont use `UnhollowerBaseLib`, have LUM report that mods that require it are no longer usable and should be updated if possible

### Describe alternatives you've considered

Cant think of anything else. 

### Additional context

This dependency was replaced in `0.6.0` of `MelonLoader` with `Il2CppInterop`

**Comment by rakosi2** [comment]
Mind sending a log that I can use to test with

**Comment by Arkhorse** [comment]
Not mine but the most recent one I can find
[orel4483_Latest.log](https://github.com/Slaynash/Lumbot/files/12363814/orel4483_Latest.log)
