### ISSUE TITLE
[FEATURE REQUEST]: Handle incompatible mods

### ISSUE THREAD

**Issue by Arkhorse** [Slaynash/Lumbot#13]
### Is your feature request related to a problem? Please describe.

Currently LUM considers incompatible mods to be `Missing Dependencies`. 

### Describe the solution you'd like

I think lum could state the two mods that are not compatible with each other. Though I do get that LUM's embed message is getting pretty big now. Might need to start splitting them up (if possible). This splitting could actually make the output more readable, if its not hard to implement that is

### Describe alternatives you've considered

LUM could take the first mod as the mod the user should keep, as this is the mod that defines the incompatible mod attribute

### Additional context

Excerpt from the log:
```
[15:37:44.169] Some Melons are marked as incompatible with each other.
To avoid any errors, these Melons will not be loaded.
- 'MapManager' is incompatible with the following Melons:
    - 'MapTweaks'
```
[IncompatibleMods.log](https://github.com/Slaynash/Lumbot/files/13316596/IncompatibleMods.log)

**Comment by rakosi2** [comment]
Lum should already be pointing this out, thank you for letting me know that it is not working. I am not sure what you mean by splitting the embed, are you saying that we should send multiple embeds?

**Comment by rakosi2** [comment]
ya, I have MissingDependencies checks a bit greedy, it is a bit annoying to fix but moving the Incompatible checks before it resolved this issue.

**Comment by Arkhorse** [comment]
> I am not sure what you mean by splitting the embed, are you saying that we should send multiple embeds?

Yes. They have a max character count so if someone happens to have alot of mods installed (which is very common) the embed wont show everything. But if every category was split into separate embeds this would be less of an issue

**Comment by rakosi2** [comment]
I am aware of the max character and Lum will limit the characters of each field, There are currently no checks between the fields but I have not hit that 6k limit once during the 3 years I have been working on Lum. It just gets visually long and breaking it into multiple embeds would make it even longer.
