### ISSUE TITLE
[BUG REPORT]: Unhelpful suggestion from LUM when an outdated mod is used that requires an old version of MelonLoader

### ISSUE THREAD

**Issue by Arkhorse** [Slaynash/Lumbot#18]
### Describe the bug

LUM will post this block of text whenever it detects that a mod requires an older ML version. This is very unhelpful for games who need a different version than the installed mod (like when a mod gets abandoned but users keep trying to use it).

A possible way to make this better is to use expected version of ML and the game version. For instance, The Long Dark's current version (2.27) requires 0.6.1. So if they are on those two versions, lum would not recommend a downgrade.

As for the pairing of the two versions, I would use exact versions instead of ranges. Not every ML version will work with a given game and sometimes new versions of ML (like 0.6.2) are entirely broken. 

Block of Text:
**Known Errors:**
A mod needs a version of MelonLoader before 0.6.x maybe try downgrading to 0.5.7 or updating that mod.

### To Reproduce

I dont know how lum detects this

### Expected behavior

N/A

**Comment by rakosi2** [comment]
Currently, I do have the ability to set a melonloader version override per game but it is currently not set up to look at the game's version to decide on which one to recommend. Currently, this is managed by me but I do not pay attention to all games so would be cool if I could have the community help manage this override.

**Comment by Arkhorse** [comment]
> Currently, I do have the ability to set a melonloader version override per game but it is currently not set up to look at the game's version to decide on which one to recommend. Currently, this is managed by me but I do not pay attention to all games so would be cool if I could have the community help manage this override.

Could make a command, something like:
`!lum-set [[game|g]|[melonloader|ml]] double`

**Comment by dommrogers** [comment]
I think I've just covered this with this PR commit
https://github.com/Slaynash/Lumbot/pull/19/commits/2255d2afacadfe1fe837804ef280654ea9a5afc1
