### ISSUE TITLE
[BUG REPORT]: New Unity Download Archive Page Format

### ISSUE THREAD

**Issue by ds5678** [Slaynash/Lumbot#21]
### Describe the bug

https://unity.com/releases/editor/archive

The page is now minified, and the normal download links have been move to sub pages, so Lum can't detect new Unity versions anymore.

### To Reproduce

Visit the link and view the page source.

### Expected behavior

Unity shouldn't change the page ever. ;)

### Additional context

The page still has everything needed for Lum to get the versions.

* Full version strings
* Unity Hub install links which contain the version id

However, Lum will likely need to use an xml parsing library.

**Comment by rakosi2** [comment]
Mostly fixed, Still have some with the Unity Extractor but I don't know how any of that works so going to leave that to Slaynash to fix.
