### ISSUE TITLE
[FEATURE REQUEST]: Some things to improve the embed

### ISSUE THREAD

**Issue by Arkhorse** [Slaynash/Lumbot#26]
### Is your feature request related to a problem? Please describe.

Yes. People can misunderstand what the information is for, this would ensure this misunderstanding is less likely.

### Describe the solution you'd like

- Currently the header is `Log Autocheck Result:`. Since this is a header, should really be `Log Autocheck Result` (removed the colon)
- Each section should have an explanation as to what the user should do about things in that section. For instance, some users will see `Mods Newer Than API` and download the old versions. This naturally causes issues as they may have downloaded a version that is known to be broken. This section could just have a generic `This section is to help the helpers, do no change anything unless you are told to`.
- If possible, link this github in the footer where it states `Lum Log Scanner`
- Beneath the main top header, there are a few things that could be added to help the helpers: Game Version, MelonLoader Version and Game Path. Game Version is useful to know if the user is on a supported version of the game. Same with the ML version. The path is useful to know if the user is not using steam, which can be an issue if modding on other platforms is not possible. I think this might require some rewrite of the regex system as I'm not sure if it can handle the capture groups or not

I think this should help a bit with the misunderstandings and add some useful information

### Describe alternatives you've considered

n/n

**Comment by rakosi2** [comment]
Yes, it can handle capture groups. Not sure what needs to be rewritten for regex.

**Comment by rakosi2** [comment]
oh ya, Discord does not allow links in the footer for some reason, it is just text and makes it too big for my liking.
